CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gist";
CREATE TYPE organization_type AS ENUM ('clinic', 'independent');
CREATE TYPE membership_role AS ENUM ('organization_admin', 'professional', 'assistant', 'independent_owner');
CREATE TYPE membership_status AS ENUM ('active', 'suspended', 'removed');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), type organization_type NOT NULL, slug varchar(120) NOT NULL UNIQUE, name varchar(160) NOT NULL, settings jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(160) NOT NULL, email varchar(320) NOT NULL UNIQUE, email_verified boolean NOT NULL DEFAULT false, image varchar(2048), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, slug varchar(120) NOT NULL, name varchar(160) NOT NULL, timezone varchar(64) NOT NULL DEFAULT 'America/Santiago', settings jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id, slug), UNIQUE(id, organization_id));
CREATE TABLE memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, role membership_role NOT NULL, status membership_status NOT NULL DEFAULT 'active', expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id, user_id), UNIQUE(id, organization_id));
CREATE TABLE membership_sites (membership_id uuid NOT NULL REFERENCES memberships(id) ON DELETE CASCADE, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(membership_id, site_id), FOREIGN KEY(membership_id, organization_id) REFERENCES memberships(id, organization_id), FOREIGN KEY(site_id, organization_id) REFERENCES sites(id, organization_id));
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, site_id uuid, actor_membership_id uuid, action varchar(120) NOT NULL, entity varchar(120) NOT NULL, entity_id uuid, before jsonb NOT NULL DEFAULT '{}', after jsonb NOT NULL DEFAULT '{}', reason varchar(500) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_organization_created_idx ON audit_logs(organization_id, created_at);

CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token varchar(255) NOT NULL UNIQUE, expires_at timestamptz NOT NULL, ip_address varchar(128), user_agent text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, account_id varchar(255) NOT NULL, provider_id varchar(255) NOT NULL, password text, access_token text, refresh_token text, id_token text, access_token_expires_at timestamptz, refresh_token_expires_at timestamptz, scope text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider_id, account_id));
CREATE TABLE verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), identifier varchar(320) NOT NULL, value text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
