"use client";
import { useMemo, useState, type FormEvent } from "react";

type View = "day" | "week";
const sampleAppointments = [{ id: "demo-1", patient: "Ana Paz · dato ficticio", time: "10:00–10:30", site: "Providencia", status: "Confirmada" }, { id: "demo-2", patient: "Bruno Solís · dato ficticio", time: "15:00–15:30", site: "Ñuñoa", status: "Pendiente" }];

export function AgendaClient() {
  const [view, setView] = useState<View>("week"); const [notice, setNotice] = useState(""); const [appointments, setAppointments] = useState(sampleAppointments);
  const heading = useMemo(() => view === "week" ? "Semana de agenda" : "Agenda del día", [view]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const start = String(data.get("start")); const end = String(data.get("end")); if (!start || !end || end <= start) { setNotice("El horario de término debe ser posterior al de inicio."); return; } if (start < "09:00" || end > "18:00") { setNotice("Ese horario está fuera de la disponibilidad configurada."); return; } setAppointments((current) => [...current, { id: crypto.randomUUID(), patient: `${data.get("patient")} · dato ficticio`, time: `${start}–${end}`, site: String(data.get("site")), status: "Pendiente" }]); setNotice("Cita preparada en la agenda. La confirmación final valida disponibilidad."); event.currentTarget.reset(); }
  return <section aria-labelledby="agenda-title"><p className="agenda-kicker">Operación clínica</p><h1 id="agenda-title">Agenda</h1><p>Organiza las citas por sede, profesional y box. Los datos de esta vista son ficticios.</p><div className="agenda-toolbar"><div role="group" aria-label="Vista de agenda"><button className={view === "day" ? "active" : ""} onClick={() => setView("day")}>Día</button><button className={view === "week" ? "active" : ""} onClick={() => setView("week")}>Semana</button></div><span>{heading}</span></div><div className="agenda-grid"><section><h2>{heading}</h2><div className="agenda-columns"><strong>Hora</strong><strong>Providencia</strong><strong>Ñuñoa</strong>{appointments.map((appointment) => <div className="appointment" key={appointment.id} draggable onDragEnd={() => setNotice("Revisa la disponibilidad antes de confirmar el cambio de horario.")}><span>{appointment.time}</span><span>{appointment.patient}</span><small>{appointment.site} · {appointment.status}</small><button onClick={() => { const reason = window.prompt("Motivo de la cancelación:"); if (!reason?.trim()) { setNotice("Indica el motivo de la cancelación."); return; } setAppointments((current) => current.filter((item) => item.id !== appointment.id)); setNotice("Cita cancelada; el historial conserva el motivo."); }}>Cancelar</button></div>)}</div></section><form className="agenda-form" onSubmit={submit}><h2>Nueva cita</h2><label>Paciente<input name="patient" required /></label><label>Sede<select name="site"><option>Providencia</option><option>Ñuñoa</option></select></label><div><label>Inicio<input name="start" type="time" required /></label><label>Término<input name="end" type="time" required /></label></div><button type="submit">Agregar a agenda</button>{notice && <p role="status" className="inline-notice">{notice}</p>}</form></div></section>;
}
