import { createHash } from "node:crypto";
export const MAX_CSV_BYTES=20*1024*1024;export const MAX_CSV_ROWS=100000;
export type CsvRow=Record<string,string>;
export type ParsedCsv={headers:string[];rows:CsvRow[];contentHash:string;byteSize:number};
export function contentHash(content:Uint8Array):string{return createHash("sha256").update(content).digest("hex");}
export function mappingHash(mapping:Record<string,string>):string{return createHash("sha256").update(JSON.stringify(Object.fromEntries(Object.entries(mapping).sort(([a],[b])=>a.localeCompare(b))))).digest("hex");}
function parseLine(line:string):string[]{const values:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i]!;if(char==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(char===","&&!quoted){values.push(value);value="";}else value+=char;}if(quoted)throw new Error("El CSV contiene comillas sin cerrar.");values.push(value);return values;}
function rowsFromRecords(records:string[]):{headers:string[];rows:CsvRow[]}{const nonEmpty=records.filter((line,index)=>line.length>0||index<records.length-1);if(nonEmpty.length<2)throw new Error("El CSV debe incluir encabezados y al menos una fila.");if(nonEmpty.length-1>MAX_CSV_ROWS)throw new Error("El CSV supera el máximo de 100000 filas.");const headers=parseLine(nonEmpty[0]!.replace(/^\uFEFF/,"")).map(value=>value.trim());if(headers.some(header=>!header)||new Set(headers).size!==headers.length)throw new Error("Los encabezados deben ser únicos y no vacíos.");const rows=nonEmpty.slice(1).map(line=>{const fields=parseLine(line);if(fields.length!==headers.length)throw new Error("Una fila no coincide con la cantidad de columnas.");return Object.fromEntries(headers.map((header,index)=>[header,fields[index]!.trim()]));});return{headers,rows};}
export function parseCsv(content:Uint8Array):{headers:string[];rows:CsvRow[]}{if(content.byteLength===0||content.byteLength>MAX_CSV_BYTES)throw new Error("El CSV debe pesar entre 1 byte y 20 MB.");const text=new TextDecoder("utf-8",{fatal:true}).decode(content);return rowsFromRecords(splitCompleteRecords(text,true));}
function splitCompleteRecords(buffer:string,final=false):string[]{const records:string[]=[];let start=0,quoted=false;for(let i=0;i<buffer.length;i++){const char=buffer[i]!;if(char==='"'){if(quoted&&buffer[i+1]==='"'){i++;continue;}quoted=!quoted;}else if(char==='\n'&&!quoted){records.push(buffer.slice(start,i).replace(/\r$/,"") );start=i+1;}}if(final){if(quoted)throw new Error("El CSV contiene comillas sin cerrar.");if(start<buffer.length)records.push(buffer.slice(start).replace(/\r$/,""));else if(buffer.endsWith("\n"))records.push("");}else records.push(buffer.slice(start));return records;}
export async function parseCsvStream(chunks:AsyncIterable<Uint8Array>):Promise<ParsedCsv>{const hash=createHash("sha256"),decoder=new TextDecoder("utf-8",{fatal:true});let byteSize=0,buffer="";const records:string[]=[];for await(const chunk of chunks){byteSize+=chunk.byteLength;if(byteSize>MAX_CSV_BYTES)throw new Error("El CSV supera el máximo de 20 MB.");hash.update(chunk);buffer+=decoder.decode(chunk,{stream:true});const split=splitCompleteRecords(buffer);buffer=split.pop()??"";records.push(...split);if(records.length-1>MAX_CSV_ROWS)throw new Error("El CSV supera el máximo de 100000 filas.");}buffer+=decoder.decode();records.push(...splitCompleteRecords(buffer,true));if(byteSize===0)throw new Error("El CSV está vacío.");return{...rowsFromRecords(records),contentHash:hash.digest("hex"),byteSize};}
