import { boolean, foreignKey, index, pgTable, smallint, unique, uuid, varchar } from "drizzle-orm/pg-core";
import { clp, createdAt, id, jsonData, organizationId, updatedAt } from "./core";
import { patients } from "./clinical";
import { memberships, organizations } from "./tenant";

export const feeSchedules = pgTable("fee_schedules", { id: id(), organizationId: organizationId().references(() => organizations.id, { onDelete: "cascade" }), code: varchar("code", { length: 64 }).notNull(), name: varchar("name", { length: 200 }).notNull(), priceClp: clp("price_clp"), active: boolean("active").notNull().default(true), validFrom: createdAt(), validUntil: createdAt(), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [unique("fee_schedules_org_code_unique").on(table.organizationId, table.code), unique("fee_schedules_id_organization_unique").on(table.id, table.organizationId)]);
export const estimates = pgTable("estimates", { id: id(), organizationId: organizationId().references(() => organizations.id, { onDelete: "cascade" }), patientId: uuid("patient_id").notNull().references(() => patients.id, { onDelete: "restrict" }), authorMembershipId: uuid("author_membership_id").notNull().references(() => memberships.id, { onDelete: "restrict" }), currentVersion: smallint("current_version").notNull().default(1), state: varchar("state", { length: 16 }).notNull().default("draft"), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [unique("estimates_id_organization_unique").on(table.id, table.organizationId), foreignKey({ columns: [table.patientId, table.organizationId], foreignColumns: [patients.id, patients.organizationId], name: "estimates_patient_tenant_fk" }), foreignKey({ columns: [table.authorMembershipId, table.organizationId], foreignColumns: [memberships.id, memberships.organizationId], name: "estimates_author_tenant_fk" }), index("estimates_patient_scope_idx").on(table.organizationId, table.patientId)]);
export const estimateVersions = pgTable("estimate_versions", { id: id(), organizationId: organizationId().references(() => organizations.id, { onDelete: "cascade" }), estimateId: uuid("estimate_id").notNull().references(() => estimates.id, { onDelete: "cascade" }), version: smallint("version").notNull(), state: varchar("state", { length: 16 }).notNull(), totalClp: clp("total_clp"), snapshot: jsonData("snapshot"), createdAt: createdAt() }, (table) => [unique("estimate_versions_id_organization_unique").on(table.id, table.organizationId), unique("estimate_versions_estimate_version_unique").on(table.estimateId, table.version), foreignKey({ columns: [table.estimateId, table.organizationId], foreignColumns: [estimates.id, estimates.organizationId], name: "estimate_versions_estimate_tenant_fk" })]);
export const estimateItems = pgTable("estimate_items", { id: id(), organizationId: organizationId().references(() => organizations.id, { onDelete: "cascade" }), estimateVersionId: uuid("estimate_version_id").notNull().references(() => estimateVersions.id, { onDelete: "cascade" }), feeScheduleId: uuid("fee_schedule_id").references(() => feeSchedules.id, { onDelete: "restrict" }), code: varchar("code", { length: 64 }).notNull(), description: varchar("description", { length: 200 }).notNull(), unitPriceClp: clp("unit_price_clp"), quantity: smallint("quantity").notNull(), discountClp: clp("discount_clp"), lineTotalClp: clp("line_total_clp") }, (table) => [foreignKey({ columns: [table.estimateVersionId, table.organizationId], foreignColumns: [estimateVersions.id, estimateVersions.organizationId], name: "estimate_items_version_tenant_fk" }), foreignKey({ columns: [table.feeScheduleId, table.organizationId], foreignColumns: [feeSchedules.id, feeSchedules.organizationId], name: "estimate_items_tariff_tenant_fk" }), index("estimate_items_version_idx").on(table.organizationId, table.estimateVersionId)]);
export const estimateLinks = pgTable("estimate_links", { id: id(), organizationId: organizationId().references(() => organizations.id, { onDelete: "cascade" }), estimateVersionId: uuid("estimate_version_id").notNull().references(() => estimateVersions.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull(), expiresAt: createdAt(), revokedAt: createdAt(), createdByMembershipId: uuid("created_by_membership_id").notNull().references(() => memberships.id, { onDelete: "restrict" }), createdAt: createdAt() }, (table) => [unique("estimate_links_token_hash_unique").on(table.tokenHash), foreignKey({ columns: [table.estimateVersionId, table.organizationId], foreignColumns: [estimateVersions.id, estimateVersions.organizationId], name: "estimate_links_version_tenant_fk" }), foreignKey({ columns: [table.createdByMembershipId, table.organizationId], foreignColumns: [memberships.id, memberships.organizationId], name: "estimate_links_actor_tenant_fk" })]);
