import type { Sql, TransactionSql } from "postgres";
import type { TenantContext } from "@/lib/tenancy";
import { can } from "@/features/tenant-identity/authorize";
import { localWeekday } from "@/features/scheduling/domain";
import { addDaysLocal, attendancePercent, dayBounds, deltaPercent, formatDayParam, occupancyPercent, todayInSantiago, type DayDate, type DayScope } from "./domain";

type DashboardSql = Sql | TransactionSql;
type CountRow = { total:string|number; confirmed:string|number; pending:string|number; patients:string|number; attended:string|number; missed:string|number; scheduledMinutes:string|number };
type FinanceRow = { collected:string|number; production:string|number; payments:string|number };
const asDate=(value:unknown):Date=>value instanceof Date?value:new Date(String(value));
export type DashboardAppointment={id:string;startsAt:Date;endsAt:Date;patientName:string;patientId:string|null;status:"pending"|"confirmed"|"cancelled";attendance:"attended"|"missed"|null;professionalMembershipId:string;professionalName:string;boxName:string|null;siteName:string|null};
export type DashboardSummary={kpis:{appointments:number;confirmed:number;pending:number;patients:number;finance:{collectedClp:number;productionClp:number;payments:number}|null};agenda:DashboardAppointment[];income:null|{collectedClp:number;productionClp:number;movements:{id:string;patientName:string;createdAt:Date;amountClp:number;kind:"charge"|"payment"}[];sparkline:{day:string;totalClp:number}[]};health:{occupancy:number|null;scheduledMinutes:number;capacityMinutes:number;attendance:number|null;marked:number;appointments:number;productionClp:number|null;collectedClp:number|null;productionDelta:number|null;collectedDelta:number|null;newPatients:number;captureDelta:number|null};estimates:null|{states:Record<string,{count:number;totalClp:number}>;recent:{id:string;patientName:string;state:string;totalClp:number;updatedAt:Date}[]};pendingClinical:null|{today:number;total:number;recent:{patientId:string;patientName:string;startsAt:Date}[]}};

export async function dashboardSummary(sql:DashboardSql,actor:TenantContext,day:DayDate,scope:DayScope):Promise<DashboardSummary>{
 const {start,end}=dayBounds(day),previous=dayBounds(addDaysLocal(day,-1)); const startIso=start.toISOString(),endIso=end.toISOString(),prevStartIso=previous.start.toISOString(),prevEndIso=previous.end.toISOString(); const own=scope==="own"; const financeAllowed=can(actor,"billing:manage"); const estimateAllowed=can(actor,"estimate:manage");
 // Sequential queries deliberately avoid concurrent statements on one transaction connection.
 const counts=await sql<CountRow[]>`SELECT count(*)::int AS total,count(*) FILTER(WHERE status='confirmed')::int AS confirmed,count(*) FILTER(WHERE status='pending')::int AS pending,count(DISTINCT lower(trim(patient_name)))::int AS patients,count(*) FILTER(WHERE attendance='attended')::int AS attended,count(*) FILTER(WHERE attendance='missed')::int AS missed,COALESCE(sum(extract(epoch FROM (ends_at-starts_at))/60),0)::int AS "scheduledMinutes" FROM appointments WHERE organization_id=${actor.organizationId} AND kind='appointment' AND status<>'cancelled' AND starts_at>=${startIso} AND starts_at<${endIso} AND (${!own} OR professional_membership_id=${actor.membershipId})`;
 const agenda=await sql<DashboardAppointment[]>`SELECT a.id,a.starts_at AS "startsAt",a.ends_at AS "endsAt",a.patient_name AS "patientName",a.patient_id AS "patientId",a.status,a.attendance,a.professional_membership_id AS "professionalMembershipId",u.name AS "professionalName",b.name AS "boxName",s.name AS "siteName" FROM appointments a JOIN memberships m ON m.id=a.professional_membership_id AND m.organization_id=a.organization_id JOIN users u ON u.id=m.user_id LEFT JOIN boxes b ON b.id=a.box_id AND b.organization_id=a.organization_id LEFT JOIN sites s ON s.id=a.site_id AND s.organization_id=a.organization_id WHERE a.organization_id=${actor.organizationId} AND a.kind='appointment' AND a.starts_at>=${startIso} AND a.starts_at<${endIso} AND (${!own} OR a.professional_membership_id=${actor.membershipId}) ORDER BY a.starts_at`;
 const capacity=await sql<{minutes:string|number}[]>`SELECT COALESCE(sum(extract(epoch FROM (ends_at-starts_at))/60),0)::int AS minutes FROM professional_availability WHERE organization_id=${actor.organizationId} AND weekday=${localWeekday(start)} AND (${!own} OR professional_membership_id=${actor.membershipId})`;
 const captures=await sql<{current:string|number;previous:string|number}[]>`SELECT count(*) FILTER(WHERE created_at>=${startIso} AND created_at<${endIso})::int AS current,count(*) FILTER(WHERE created_at>=${prevStartIso} AND created_at<${prevEndIso})::int AS previous FROM patients WHERE organization_id=${actor.organizationId}`;
 let finance:FinanceRow={collected:0,production:0,payments:0},previousFinance:FinanceRow={collected:0,production:0,payments:0}; let income:DashboardSummary["income"]=null;
 if(financeAllowed){
  finance=(await sql<FinanceRow[]>`SELECT COALESCE(sum(amount_clp) FILTER(WHERE kind='payment'),0) AS collected,COALESCE(sum(amount_clp) FILTER(WHERE kind='charge'),0) AS production,count(*) FILTER(WHERE kind='payment')::int AS payments FROM billing_movements WHERE organization_id=${actor.organizationId} AND status='posted' AND created_at>=${startIso} AND created_at<${endIso} AND (${!own} OR professional_membership_id=${actor.membershipId})`)[0];
  previousFinance=(await sql<FinanceRow[]>`SELECT COALESCE(sum(amount_clp) FILTER(WHERE kind='payment'),0) AS collected,COALESCE(sum(amount_clp) FILTER(WHERE kind='charge'),0) AS production,count(*) FILTER(WHERE kind='payment')::int AS payments FROM billing_movements WHERE organization_id=${actor.organizationId} AND status='posted' AND created_at>=${prevStartIso} AND created_at<${prevEndIso} AND (${!own} OR professional_membership_id=${actor.membershipId})`)[0];
  const movements=await sql<{id:string;patientName:string;createdAt:Date;amountClp:string|number;kind:"charge"|"payment"}[]>`SELECT bm.id,p.first_name||' '||p.last_name AS "patientName",bm.created_at AS "createdAt",bm.amount_clp AS "amountClp",bm.kind FROM billing_movements bm JOIN patients p ON p.id=bm.patient_id AND p.organization_id=bm.organization_id WHERE bm.organization_id=${actor.organizationId} AND bm.status='posted' AND bm.kind IN ('charge','payment') AND bm.created_at>=${startIso} AND bm.created_at<${endIso} AND (${!own} OR bm.professional_membership_id=${actor.membershipId}) ORDER BY bm.created_at DESC LIMIT 5`;
  const sparkStart=dayBounds(addDaysLocal(day,-6)).start; const raw=await sql<{day:string;totalClp:string|number}[]>`SELECT to_char((created_at AT TIME ZONE 'America/Santiago')::date,'YYYY-MM-DD') AS day,sum(amount_clp) AS "totalClp" FROM billing_movements WHERE organization_id=${actor.organizationId} AND status='posted' AND kind='payment' AND created_at>=${sparkStart.toISOString()} AND created_at<${endIso} AND (${!own} OR professional_membership_id=${actor.membershipId}) GROUP BY 1 ORDER BY 1`; const map=new Map(raw.map(r=>[r.day,Number(r.totalClp)])); const sparkline=Array.from({length:7},(_,i)=>{const d=formatDayParam(addDaysLocal(day,i-6));return{day:d,totalClp:map.get(d)??0}});
  income={collectedClp:Number(finance.collected),productionClp:Number(finance.production),movements:movements.map(m=>({...m,createdAt:asDate(m.createdAt),amountClp:Number(m.amountClp)})),sparkline};
 }
 let estimates:DashboardSummary["estimates"]=null;
 if(estimateAllowed){const stateRows=await sql<{state:string;count:string|number;totalClp:string|number}[]>`SELECT e.state,count(*)::int AS count,COALESCE(sum(ev.total_clp),0) AS "totalClp" FROM estimates e JOIN estimate_versions ev ON ev.estimate_id=e.id AND ev.organization_id=e.organization_id AND ev.version=e.current_version WHERE e.organization_id=${actor.organizationId} GROUP BY e.state`;const recent=await sql<{id:string;patientName:string;state:string;totalClp:string|number;updatedAt:Date}[]>`SELECT e.id,p.first_name||' '||p.last_name AS "patientName",e.state,ev.total_clp AS "totalClp",e.updated_at AS "updatedAt" FROM estimates e JOIN estimate_versions ev ON ev.estimate_id=e.id AND ev.organization_id=e.organization_id AND ev.version=e.current_version JOIN patients p ON p.id=e.patient_id AND p.organization_id=e.organization_id WHERE e.organization_id=${actor.organizationId} ORDER BY e.updated_at DESC LIMIT 5`;const states=Object.fromEntries(["draft","sent","approved","rejected","expired"].map(s=>[s,{count:0,totalClp:0}]));for(const r of stateRows)states[r.state]={count:Number(r.count),totalClp:Number(r.totalClp)};estimates={states,recent:recent.map(r=>({...r,updatedAt:asDate(r.updatedAt),totalClp:Number(r.totalClp)}))};}
 let pendingClinical:DashboardSummary["pendingClinical"]=null;
 if(actor.role!=="assistant"){const today=dayBounds(todayInSantiago());const rawRows=await sql<{patientId:string;patientName:string;startsAt:Date}[]>`SELECT a.patient_id AS "patientId",a.patient_name AS "patientName",a.starts_at AS "startsAt" FROM appointments a WHERE a.organization_id=${actor.organizationId} AND a.kind='appointment' AND a.status<>'cancelled' AND a.patient_id IS NOT NULL AND a.attendance IS DISTINCT FROM 'missed' AND a.starts_at<=now() AND (${!own} OR a.professional_membership_id=${actor.membershipId}) AND NOT EXISTS(SELECT 1 FROM clinical_records cr WHERE cr.organization_id=a.organization_id AND cr.patient_id=a.patient_id AND cr.occurred_at>=a.starts_at) ORDER BY a.starts_at DESC`;const rows=rawRows.map(r=>({...r,startsAt:asDate(r.startsAt)}));pendingClinical={today:rows.filter(r=>r.startsAt>=today.start&&r.startsAt<today.end).length,total:rows.length,recent:rows.slice(0,5)};}
 const c=counts[0],cap=Number(capacity[0]?.minutes??0),capt=captures[0]; return{kpis:{appointments:Number(c.total),confirmed:Number(c.confirmed),pending:Number(c.pending),patients:Number(c.patients),finance:financeAllowed?{collectedClp:Number(finance.collected),productionClp:Number(finance.production),payments:Number(finance.payments)}:null},agenda:agenda.map(a=>({...a,startsAt:asDate(a.startsAt),endsAt:asDate(a.endsAt)})),income,health:{occupancy:occupancyPercent(Number(c.scheduledMinutes),cap),scheduledMinutes:Number(c.scheduledMinutes),capacityMinutes:cap,attendance:attendancePercent(Number(c.attended),Number(c.missed)),marked:Number(c.attended)+Number(c.missed),appointments:Number(c.total),productionClp:financeAllowed?Number(finance.production):null,collectedClp:financeAllowed?Number(finance.collected):null,productionDelta:financeAllowed?deltaPercent(Number(finance.production),Number(previousFinance.production)):null,collectedDelta:financeAllowed?deltaPercent(Number(finance.collected),Number(previousFinance.collected)):null,newPatients:Number(capt.current),captureDelta:deltaPercent(Number(capt.current),Number(capt.previous))},estimates,pendingClinical};
}
