import type { Sql, TransactionSql } from "postgres";
import type { TenantContext } from "@/lib/tenancy";
import { authorize } from "@/features/tenant-identity/authorize";
import { assertEstimateRevisionAllowed, assertEstimateShareable, calculateEstimate, hashEstimateToken, nextEstimateState, publicEstimateToken, type EstimateLine, type EstimateState } from "./domain";
export type TariffLine = { feeScheduleId: string; quantity: number; discountClp?: number };
type EstimateSql = Sql | TransactionSql;
type TariffRow = { id: string; code: string; name: string; priceClp: string | number };
async function resolveTariffLines(sql: EstimateSql, organizationId: string, lines: readonly TariffLine[]): Promise<EstimateLine[]> { const resolved: EstimateLine[] = []; for (const line of lines) { const tariff = (await sql<TariffRow[]>`SELECT id, code, name, price_clp AS "priceClp" FROM fee_schedules WHERE id=${line.feeScheduleId} AND organization_id=${organizationId} AND active`)[0]; if (!tariff) throw new Error("La prestación seleccionada no pertenece al arancel vigente."); resolved.push({ code: tariff.code, description: tariff.name, unitPriceClp: Number(tariff.priceClp), quantity: line.quantity, discountClp: line.discountClp }); } return resolved; }
async function insertVersion(sql: EstimateSql, organizationId: string, estimateId: string, version: number, state: EstimateState, lines: readonly TariffLine[]): Promise<string> { const calculated = calculateEstimate(await resolveTariffLines(sql, organizationId, lines)); const result = (await sql<{id:string}[]>`INSERT INTO estimate_versions (organization_id,estimate_id,version,state,total_clp,snapshot) VALUES (${organizationId},${estimateId},${version},${state},${calculated.totalClp},${JSON.stringify(calculated)}::jsonb) RETURNING id`)[0]!; for (let i=0;i<calculated.lines.length;i++) { const line=calculated.lines[i]!; await sql`INSERT INTO estimate_items (organization_id,estimate_version_id,fee_schedule_id,code,description,unit_price_clp,quantity,discount_clp,line_total_clp) VALUES (${organizationId},${result.id},${lines[i]!.feeScheduleId},${line.code},${line.description},${line.unitPriceClp},${line.quantity},${line.discountClp??0},${line.lineTotalClp})`; } return result.id; }
export async function createEstimate(sql: EstimateSql, actor: TenantContext, patientId: string, lines: readonly TariffLine[]): Promise<string> { authorize(actor,"estimate:manage"); const estimate=(await sql<{id:string}[]>`INSERT INTO estimates (organization_id,patient_id,author_membership_id) VALUES (${actor.organizationId},${patientId},${actor.membershipId}) RETURNING id`)[0]!; await insertVersion(sql,actor.organizationId,estimate.id,1,"draft",lines); return estimate.id; }
export async function reviseEstimate(sql: EstimateSql, actor: TenantContext, estimateId: string, previousVersion: number, lines: readonly TariffLine[]): Promise<void> { authorize(actor,"estimate:manage"); const current=(await sql<{state:EstimateState}[]>`SELECT state FROM estimates WHERE id=${estimateId} AND organization_id=${actor.organizationId} AND current_version=${previousVersion} FOR UPDATE`)[0]; if(!current) throw new Error("La cotización no está en la versión esperada."); assertEstimateRevisionAllowed(current.state); await insertVersion(sql,actor.organizationId,estimateId,previousVersion+1,"draft",lines); const updated=await sql`UPDATE estimates SET current_version=${previousVersion+1},state='draft',updated_at=now() WHERE id=${estimateId} AND organization_id=${actor.organizationId} AND current_version=${previousVersion}`; if(updated.count!==1) throw new Error("La cotización no está en la versión esperada."); await sql`INSERT INTO estimate_transitions (organization_id,estimate_id,actor_membership_id,from_state,to_state) VALUES (${actor.organizationId},${estimateId},${actor.membershipId},${current.state},'draft')`; }
export async function transitionEstimate(sql: EstimateSql, actor: TenantContext, estimateId: string, current: EstimateState, target: EstimateState): Promise<void> { authorize(actor,"estimate:manage"); nextEstimateState(current,target); const estimates=await sql<{currentVersion:number}[]>`UPDATE estimates SET state=${target},updated_at=now() WHERE id=${estimateId} AND organization_id=${actor.organizationId} AND state=${current} RETURNING current_version AS "currentVersion"`; if(estimates.length!==1) throw new Error("La cotización no está en el estado esperado."); await sql`UPDATE estimate_versions SET state=${target} WHERE organization_id=${actor.organizationId} AND estimate_id=${estimateId} AND version=${estimates[0]!.currentVersion}`; await sql`INSERT INTO estimate_transitions (organization_id,estimate_id,actor_membership_id,from_state,to_state) VALUES (${actor.organizationId},${estimateId},${actor.membershipId},${current},${target})`; }
export async function shareEstimate(sql: EstimateSql, actor: TenantContext, estimateVersionId: string, expiresAt?: Date): Promise<string> { authorize(actor,"estimate:manage"); const version=(await sql<{state:EstimateState}[]>`SELECT v.state FROM estimate_versions v JOIN estimates e ON e.id=v.estimate_id AND e.organization_id=v.organization_id AND e.current_version=v.version WHERE v.id=${estimateVersionId} AND v.organization_id=${actor.organizationId}`)[0]; if(!version) throw new Error("Solo se puede compartir la versión vigente."); assertEstimateShareable(version.state); const token=publicEstimateToken(); await sql`INSERT INTO estimate_links (organization_id,estimate_version_id,token_hash,expires_at,created_by_membership_id) VALUES (${actor.organizationId},${estimateVersionId},${hashEstimateToken(token)},${expiresAt??null},${actor.membershipId})`; return token; }
export async function revokeEstimateLink(sql: EstimateSql, actor: TenantContext, token:string):Promise<void>{ authorize(actor,"organization:manage"); await sql`UPDATE estimate_links SET revoked_at=now() WHERE organization_id=${actor.organizationId} AND token_hash=${hashEstimateToken(token)}`; }
type PublicItemRow={code:string;description:string;quantity:number;lineTotalClp:string|number}; type PublicEstimateRow={totalClp:string|number;state:EstimateState;items:PublicItemRow[]};
export async function publicEstimateByToken(sql:Sql,token:string):Promise<{totalClp:number;state:EstimateState;items:Array<{code:string;description:string;quantity:number;lineTotalClp:number}>}|null>{ const row=(await sql<PublicEstimateRow[]>`SELECT total_clp AS "totalClp",state,items FROM app_public_estimate_by_token(${hashEstimateToken(token)})`)[0]; return row?{totalClp:Number(row.totalClp),state:row.state,items:row.items.map(item=>({code:item.code,description:item.description,quantity:Number(item.quantity),lineTotalClp:Number(item.lineTotalClp)}))}:null; }
